name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_and_release:
    name: Build and Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            build_script: npm run package:mac
            artifact_path: release/*.dmg
          - os: windows-latest
            build_script: npm run package:win
            artifact_path: release/*.exe
          - os: ubuntu-latest
            build_script: npm run package:linux
            artifact_path: |
              release/*.deb
              release/*.tar.gz
              release/*.AppImage

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package Application
        run: ${{ matrix.build_script }}

      - name: Upload Binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
